-- 模型调用流水表-百度反欺诈模型
CREATE TABLE "AIRM_FXGD_MODEL_INVOKE_BAIDU"(
    ID NUMBER(20) PRIMARY KEY,
    APP_NO VARCHAR2(150),
    SESSION_ID VARCHAR2(150),
    CUST_ID VARCHAR2(60),
    BLACK_LEVEL VARCHAR2(15),
    BLACK_SCORE NUMBER(15),
    SCORE NUMBER(15),
    SCORE_INFO NUMBER(15),
    AFR_RESULT_BD NUMBER(15),
    AFR_RESULT_BD_INFO VARCHAR2(60),
    MODEL_RESULT VARCHAR2(255),
    CREATE_TIME VARCHAR2(255)
	)
TABLESPACE "FENQILE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;

