-- 模型调用流水表-征信反欺诈模型
CREATE TABLE "FENQILE"."AIRM_FXGD_MODEL_INVOKE_ZHENXIN" (
    "ID" NUMBER(20) PRIMARY KEY,
    "APP_NO" VARCHAR2(100),
    "SESSION_ID" VARCHAR2(100),
	  "CUST_ID" VARCHAR2(60),
    "CD_AMT" NUMBER(15,8),
    "CD_STAT" VARCHAR2(60),
    "CLASS5STATE" NUMBER(15),
    "FRAUD_INFO" VARCHAR2(60),
    "LOAN_STAT" VARCHAR2(60),
    "POS_BAL" NUMBER(15,8),
    "PUB_CNT" NUMBER(15),
    "PUB_AMT" NUMBER(15,8),
    "REPAYMENTDUTY_INFO" VARCHAR2(60),
    "RH_CRC_PRO" NUMBER(15,2),
    "RH_M12_CRC_QY_NUM" NUMBER(15),
    "RH_M12_LN_QY_NUM" NUMBER(15),
    "RH_M12_QY_NUM" NUMBER(15),
    "RH_M1_QY_NUM" NUMBER(15),
    "RH_M24_ACC_OVD_NUM" NUMBER(15),
    "RH_M24_CON_OVD_NUM" NUMBER(15),
    "RH_M3_QY_NUM" NUMBER(15),
    "RH_ORG_NUM" NUMBER(15),
    "SPECIALTRADE_TYPE" VARCHAR2(60),
    "SUM" NUMBER(15),
    "UNPAID_FLAG" VARCHAR2(60),
    "CASESTATE" VARCHAR2(60),
    "AFR_RESULT_ZX" VARCHAR2(60 BYTE),
    "AFR_RESULT_ZX_INFO" VARCHAR2(60 BYTE),
	  "MODEL_RESULT" VARCHAR2(255 BYTE) ,
    "CREATE_TIME" VARCHAR2(255 BYTE)
)
TABLESPACE "FENQILE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
