-- 模型调用流水表-客户分群策略模型
CREATE TABLE "AIRM_FXGD_MODEL_INVOKE_CUSTSEG" (
    "ID" NUMBER(20) PRIMARY KEY,
    "APP_NO" VARCHAR2(100),
		"SESSION_ID" VARCHAR2(100),
		"CUST_ID" VARCHAR2(60),
		"CUST_SCORE" NUMBER(15),
    "PROD_SCORE" NUMBER(15),
		"VARIFIELDINCOME_VAL" NUMBER(15,8),
		"FINAL_CUST_LEVEL" VARCHAR2(60 BYTE),
		"APPLY_AMT" NUMBER(15,8),
"REFUSE_CODE" NUMBER(15,8),
"CUST_SEG" VARCHAR2(60),
    "SCOREREVOLOAN" NUMBER(15,8),
    "MODEL_RESULT" VARCHAR2(255 BYTE),
    "CREATE_TIME" VARCHAR2(255 BYTE)
)
TABLESPACE "FENQILE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUSTSEG"."ID" IS '主键';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUSTSEG"."SESSION_ID" IS '唯一流水号';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUSTSEG"."APP_NO" IS '申请编号';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUSTSEG"."MODEL_RESULT" IS '响应标识';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUSTSEG"."CREATE_TIME" IS '调用时间';
