-- 寿险保单信息列表
CREATE TABLE AIRM_FXGD_INSURE_LIST(
    ID NUMBER(20) PRIMARY KEY,
    APP_NO VARCHAR2(100),
    SESSION_ID VARCHAR2(100),

    RISK_PREMIUM NUMBER(15, 2),
    EFFECT_TIME VARCHAR2(8),
    PAY_FREQUENCY VARCHAR2(8),
    INSURE_TYPE VARCHAR2(500)

);
