--字典表
CREATE TABLE AIRM_FXGD_DICT(
    ID NUMBER(20) PRIMARY KEY,
    TYPE VARCHAR2(30) NOT NULL,
    TYPE_VALUE NUMBER(20,2) NOT NULL
);

INSERT INTO AIRM_FXGD_DICT(ID, TYPE, TYPE_VALUE) VALUES(1, 'totalApplyAmt', 0);
