CREATE TABLE "AIRM_FXGD_LOG_INFO" (
    "ID" NUMBER(20) PRIMARY KEY,
    "SESSION_ID" VARCHAR2(100 BYTE),
	"METHOD_NAME" VARCHAR2(300 BYTE),
	"LOG_MESSAGE" CLOB,
	"CREATE_TIME" VARCHAR2 (50 BYTE),
	"BUSINESS_NAME" VARCHAR2(100 BYTE)
)
TABLESPACE "FENQILE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;





COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_LOG_INFO"."ID" IS '主键';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_LOG_INFO"."SESSION_ID" IS '唯一流水号';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_LOG_INFO"."BUSINESS_NAME" IS '业务名';
