-- 模型调用流水表-天谕反欺诈模型
CREATE TABLE "AIRM_FXGD_MODEL_INVOKE_TIANYU" (
    "ID" NUMBER(20) PRIMARY KEY,
    "APP_NO" VARCHAR2(100),
    "SESSION_ID" VARCHAR2(100),
	  "CUST_ID" VARCHAR2(60),
    "FOUND" NUMBER(15),
    "RISKSCORE" NUMBER(15,8),
    "RISKCODE_LENGTH" NUMBER(15),
    "RISKCODE" VARCHAR2(100),
    "RISKCODEVALUE" VARCHAR2(100),
    "AFR_RESULT_TY" VARCHAR2(60BYTE),
    "AFR_RESULT_TY_INFO" VARCHAR2(60 BYTE),
	  "MODEL_RESULT" VARCHAR2(255 BYTE) ,
    "CREATE_TIME" VARCHAR2(255 BYTE) 
)
TABLESPACE "FENQILE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
