-- 模型调用流水表-客户卡1.0模型
CREATE TABLE "AIRM_FXGD_MODEL_INVOKE_CUST1" (
    "ID" NUMBER(20) PRIMARY KEY,
    "APP_NO" VARCHAR2(100),
    "SESSION_ID" VARCHAR2(100),
	"CUST_ID" VARCHAR2(60),
    "RH_M24_CRC_OVD_MAX_PERD" NUMBER(15),
    "RH_CRC_UC_MAX_AGE" NUMBER(15),
    "RH_LN_UC_MIN_AGE" NUMBER(15),
    "RH_CRC_OVD_AMT"  NUMBER(15,8),
    "RH_CRC_UD_PRO"  NUMBER(15,8),
    "RH_M24_CR_OVD_MON" NUMBER(15),
    "RH_M12_CRC_QY_NUM" NUMBER(15),
    "RH_M12_LN_QY_NUM" NUMBER(15),
    "SCORE" NUMBER (15),
    "MODEL_RESULT" VARCHAR2(255 BYTE) ,
    "CREATE_TIME" VARCHAR2(255 BYTE)
)
TABLESPACE "FENQILE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;



COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUST1"."ID" IS '主键';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUST1"."SESSION_ID" IS '唯一流水号';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUST1"."APP_NO" IS '申请编号';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUST1"."MODEL_RESULT" IS '响应标识';
COMMENT ON COLUMN "FENQILE"."AIRM_FXGD_MODEL_INVOKE_CUST1"."CREATE_TIME" IS '调用时间';



