-- 车辆信息列表
CREATE TABLE AIRM_FXGD_VEHICLE_LIST(
    ID NUMBER(20) PRIMARY KEY,
    APP_NO VARCHAR2(100),
    SESSION_ID VARCHAR2(100),

    PURCHASE_PRICE NUMBER(15,2),
    REGISTER_DATE VARCHAR2(8),
    VEHICLE_AGE NUMBER(3,0),
    LICENSE_PLATE_NO VARCHAR2(20)
);
