-- 模型调用流水表-资质卡模型
CREATE TABLE "AIRM_FXGD_MODEL_INVOKE_ZIZHI" (
    "ID" NUMBER(20) PRIMARY KEY,
    "APP_NO" VARCHAR2(100 BYTE),
    "SESSION_ID" VARCHAR2(100 BYTE),
  	"CUST_ID" VARCHAR2(60),
	  "DEBT" NUMBER(20,8),
    "DEBT_ZX" NUMBER(15,8),
    "HOUSE_INST_AMT" NUMBER(15,8),
    "HOUSE_INST_AMT_ZX" NUMBER(15,8),
    "VARIFIELDINCOME_VAL" NUMBER(15,8),
    "INSUR_MOB" NUMBER(15),
    "FINALCUSTLEVEL" VARCHAR2(60),
    "INST_PREMIUM" NUMBER(15,8),
    "VEH_PRICE" NUMBER(15,8),
    "SALARYINCOME" NUMBER(15,8),
    "APPLYAMT" NUMBER(15,8),
    "PRODSCORE" NUMBER (15),
    "MODEL_RESULT" VARCHAR2(255 BYTE), 
    "CREATE_TIME" VARCHAR2(255 BYTE) 
	)
TABLESPACE "FENQILE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
