-- 模型调用流水表-百融反欺诈模型
CREATE TABLE "AIRM_FXGD_MODEL_INVOKE_BAIRONG" (
    "ID" NUMBER(20) PRIMARY KEY,
    "APP_NO"     VARCHAR2(100),
    "SESSION_ID"     VARCHAR2(100),
    "CUST_ID" VARCHAR2(60),
    "ALS_D7_CELL_BANK_ALLNUM" NUMBER(15),
    "ALS_D7_CELL_NBANK_ORGNUM"  NUMBER(15),
    "ALS_D7_ID_BANK_ORGNUM"  NUMBER(15),
    "ALS_D7_ID_NBANK_ORGNUM"  NUMBER(15),
    "ALS_M1_CELL_BANK_ORGNUM"  NUMBER(15),
    "ALS_M1_CELL_NBANK_ORGNUM"  NUMBER(15),
    "ALS_M1_ID_BANK_ORGNUM"  NUMBER(15),
    "ALS_M1_ID_NBANK_ORGNUM"  NUMBER(15),
    "ALS_M3_CELL_AVG_MONNUM"  NUMBER(15,8),
    "ALS_M3_CELL_MAX_MONNUM"  NUMBER(15),
    "ALS_M3_CELL_NBANK_ALLNUM"  NUMBER(15),
    "ALS_M3_CELL_NBANK_ORGNUM"  NUMBER(15),
    "ALS_M3_ID_AVG_MONNUM"  NUMBER(15,8),
    "ALS_M3_ID_MAX_MONNUM"  NUMBER(15),
    "ALS_M3_ID_NBANK_ALLNUM"  NUMBER(15),
    "ALS_M3_ID_NBANK_ORGNUM"  NUMBER(15),
    "IR_ID_X_CELL_CNT"  NUMBER(15),
    "IR_ID_X_MAIL_CNT"  NUMBER(15),
    "IR_ID_X_NAME_CNT"  NUMBER(15),
    "SCOREAFREVOLOAN"  NUMBER(15,8),
    "SL_ID_NBANK_BAD_ALLNUM"  NUMBER(15),
    "SL_ID_NBANK_LOST_ALLNUM"  NUMBER(15),
    "SL_ID_NBANK_OVERDUE_ALLNUM"  NUMBER(15),
    "TL_CELL_PDL_ORGNUM"  NUMBER(15),
    "TL_ID_PDL_ORGNUM"  NUMBER(15),
    "TL_M1_CELL_NOBANK_NEWALLNUM"  NUMBER(15),
    "TL_M1_CELL_NOBANK_NEWORGNUM"  NUMBER(15),
    "TL_M1_CELL_NOBANK_PASSNUM"  NUMBER(15),
    "TL_M1_ID_NOBANK_NEWALLNUM"  NUMBER(15),
    "TL_M1_ID_NOBANK_NEWORGNUM"  NUMBER(15),
    "TL_M1_ID_NOBANK_PASSNUM"  NUMBER(15),
    "TL_M3_CELL_NOBANK_NEWALLNUM"  NUMBER(15),
    "TL_M3_CELL_NOBANK_NEWORGNUM"  NUMBER(15),
    "TL_M3_CELL_NOBANK_PASSNUM"  NUMBER(15),
    "TL_M3_ID_NOBANK_NEWALLNUM"  NUMBER(15),
    "TL_M3_ID_NOBANK_NEWORGNUM"  NUMBER(15),
    "TL_M3_ID_NOBANK_PASSNUM"  NUMBER(15),
    "AFR_RESULT_BR2" VARCHAR2(60 BYTE),
    "AFR_RESULT_BR2_INFO" VARCHAR2(60 BYTE),
    "MODEL_RESULT"     VARCHAR2(255 BYTE) ,
    "CREATE_TIME"     VARCHAR2(255 BYTE)
)
TABLESPACE "FENQILE"
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT;
