--联通支付--
CREATE TABLE "AIRM"."LTZF_INFO" (
            STORE_ID VARCHAR2(50),
            STORE_NAME VARCHAR2(256),
            STORE_PROVINCE_CODE VARCHAR2(16),
            STORE_CITY_CIDE VARCHAR2(16),
            STORE_ZONE_CODE VARCHAR2(16),
            STORE_ADDRESS_DETAIL VARCHAR2(16),
            SALES_NAME VARCHAR2(64),
            SALES_PHONE VARCHAR2(11),
            SALES_ID VARCHAR2(32),
            CMDTY_NAME VARCHAR2(128),
            CMDTY_PRICE VARCHAR2(20),
            LOAN_AMT VARCHAR2(20),
            LOAN_TERM VARCHAR2(5),
            CATEGORY VARCHAR2(32),
            CLIENT_ID VARCHAR2(32),
            TYPE VARCHAR2(64),
            LONGITUDE VARCHAR2(32),
            LATITUDE VARCHAR2(32),
            ACCURACY NUMBER,
            BRAND_NAME VARCHAR2(64),
            MODEL_NAME VARCHAR2(64),
            DOWN_PMT_AMT VARCHAR2(20),
            NAME VARCHAR2(64),
            ID_CARD_NO VARCHAR2(18),
            ID_CARD_BEGIN_DATE VARCHAR2(10),
            ID_CARD_END_DATE VARCHAR2(10),
            ABODE_DETAIL VARCHAR2(256),
            NAME_FLAG VARCHAR2(2),
            ID_CARD_NO_FLAG VARCHAR2(2),
            ID_CARD_IN_DATE_FLAG VARCHAR2(2),
            NAME_MODIFY VARCHAR2(64),
            ID_CARD_NO_MODIFY VARCHAR2(64),
            ID_CARD_BEGIN_DATE_MODIFY VARCHAR2(10),
            ID_CARD_END_DATE_MODIFY VARCHAR2(10),
            BANK_CARD_NO VARCHAR2(32),
            BANK_PHONE VARCHAR2(11),
            BANK_ACCOUNT_NAME VARCHAR2(64),
            ABODE_STATE_CODE VARCHAR2(16),
            ABODE_CITY_CODE VARCHAR2(16),
            ABODE_ZONE_CODE VARCHAR2(16),
            ABODE_DETAIL_ADDRESS VARCHAR2(256),
            MARITAL_STATUS VARCHAR2(2),
            MOUTH_INCOME VARCHAR2(20),
            SOCIAL_IDENTITY VARCHAR2(16),
            STUDENT_FLAG VARCHAR2(1),
            APPLY_PHONE_NO VARCHAR2(11),
            APPLY_PHONE_OS VARCHAR2(64),
            APPLY_WZF_TIME VARCHAR2(14),
            UNIT_NAME VARCHAR2(128),
            EMP_PHONE VARCHAR2(16),
            EMP_PROVINCE_CODE VARCHAR2(16),
            EMP_CITY_CODE VARCHAR2(16),
            EMP_ZONE_CODE VARCHAR2(16),
            EMP_ADDR VARCHAR2(30),
            CONTACT_LIST CLOB,
            AUTH_NUMBER VARCHAR2(1024),
            OUT_ORDER_ID VARCHAR2(50),
            APP_NO VARCHAR2(50),
            TOTAL_AMT VARCHAR2(20),
            USER_NO VARCHAR2(15),
            NOTYFY_URL VARCHAR2(1024),
            MER_NAME VARCHAR2(128),
            CURRENT_STORE_FLAG VARCHAR2(1),
            SALE_ADDRESS VARCHAR2(1),
            BIZ_LICENCE_NO VARCHAR2(100),
            BIZ_LICENCE_NAME VARCHAR2(100),
            RESERVE1 VARCHAR2(100),
            RESERVE2 VARCHAR2(100),
            RESERVE3 VARCHAR2(100),
);

COMMENT ON COLUMN "LTZF_INFO"."STORE_ID" IS '门店编码';
COMMENT ON COLUMN "LTZF_INFO"."STORE_NAME" IS '门店名称';
COMMENT ON COLUMN "LTZF_INFO"."STORE_PROVINCE_CODE" IS '门店省编码';
COMMENT ON COLUMN "LTZF_INFO"."STORE_CITY_CIDE" IS '门店市编码';
COMMENT ON COLUMN "LTZF_INFO"."STORE_ZONE_CODE" IS '门店区编码';
COMMENT ON COLUMN "LTZF_INFO"."STORE_ADDRESS_DETAIL" IS '门店详细地址';
COMMENT ON COLUMN "LTZF_INFO"."SALES_NAME" IS '营业员姓名';
COMMENT ON COLUMN "LTZF_INFO"."SALES_PHONE" IS '营业员电话号码';
COMMENT ON COLUMN "LTZF_INFO"."SALES_ID" IS '营业员编号';
COMMENT ON COLUMN "LTZF_INFO"."CMDTY_NAME" IS '商品名称';
COMMENT ON COLUMN "LTZF_INFO"."CMDTY_PRICE" IS '商品价格';
COMMENT ON COLUMN "LTZF_INFO"."LOAN_AMT" IS '分期金额';
COMMENT ON COLUMN "LTZF_INFO"."LOAN_TERM" IS '分期数';
COMMENT ON COLUMN "LTZF_INFO"."CATEGORY" IS '商品类别';
COMMENT ON COLUMN "LTZF_INFO"."CLIENT_ID" IS '设备IMEI码';
COMMENT ON COLUMN "LTZF_INFO"."TYPE" IS '定位坐标系类型';
COMMENT ON COLUMN "LTZF_INFO"."LONGITUDE" IS 'GPS经度';
COMMENT ON COLUMN "LTZF_INFO"."LATITUDE" IS 'GPS维度';
COMMENT ON COLUMN "LTZF_INFO"."ACCURACY" IS '定位精度';
COMMENT ON COLUMN "LTZF_INFO"."BRAND_NAME" IS '品牌';
COMMENT ON COLUMN "LTZF_INFO"."MODEL_NAME" IS '机型';
COMMENT ON COLUMN "LTZF_INFO"."DOWN_PMT_AMT" IS '首付款';
COMMENT ON COLUMN "LTZF_INFO"."NAME" IS '姓名';
COMMENT ON COLUMN "LTZF_INFO"."ID_CARD_NO" IS '身份证号';
COMMENT ON COLUMN "LTZF_INFO"."ID_CARD_BEGIN_DATE" IS '身份证有效期(起)';
COMMENT ON COLUMN "LTZF_INFO"."ID_CARD_END_DATE" IS '身份证有效期(止)';
COMMENT ON COLUMN "LTZF_INFO"."ABODE_DETAIL" IS '住址';
COMMENT ON COLUMN "LTZF_INFO"."NAME_FLAG" IS '姓名是否修改';
COMMENT ON COLUMN "LTZF_INFO"."ID_CARD_NO_FLAG" IS '身份证号是否修改';
COMMENT ON COLUMN "LTZF_INFO"."ID_CARD_IN_DATE_FLAG" IS '身份证有效期是否修改';
COMMENT ON COLUMN "LTZF_INFO"."NAME_MODIFY" IS '修改后姓名';
COMMENT ON COLUMN "LTZF_INFO"."ID_CARD_NO_MODIFY" IS '修改后身份证号';
COMMENT ON COLUMN "LTZF_INFO"."ID_CARD_BEGIN_DATE_MODIFY" IS '修改后身份证有效期(起)';
COMMENT ON COLUMN "LTZF_INFO"."ID_CARD_END_DATE_MODIFY" IS '修改后身份证有效期(止)';
COMMENT ON COLUMN "LTZF_INFO"."BANK_CARD_NO" IS '银行卡号';
COMMENT ON COLUMN "LTZF_INFO"."BANK_PHONE" IS '银行预留手机号';
COMMENT ON COLUMN "LTZF_INFO"."BANK_ACCOUNT_NAME" IS '银行卡姓名';
COMMENT ON COLUMN "LTZF_INFO"."ABODE_STATE_CODE" IS '居住地址省code';
COMMENT ON COLUMN "LTZF_INFO"."ABODE_CITY_CODE" IS '居住地址市code';
COMMENT ON COLUMN "LTZF_INFO"."ABODE_ZONE_CODE" IS '居住地址区县code';
COMMENT ON COLUMN "LTZF_INFO"."ABODE_DETAIL_ADDRESS" IS '居住详细地址';
COMMENT ON COLUMN "LTZF_INFO"."MARITAL_STATUS" IS '婚姻状况';
COMMENT ON COLUMN "LTZF_INFO"."MOUTH_INCOME" IS '月收入';
COMMENT ON COLUMN "LTZF_INFO"."SOCIAL_IDENTITY" IS '社会身份';
COMMENT ON COLUMN "LTZF_INFO"."STUDENT_FLAG" IS '是否学生';
COMMENT ON COLUMN "LTZF_INFO"."APPLY_PHONE_NO" IS '申请人手机号';
COMMENT ON COLUMN "LTZF_INFO"."APPLY_PHONE_OS" IS '用户申请沃支付使用的手机';
COMMENT ON COLUMN "LTZF_INFO"."APPLY_WZF_TIME" IS '用户注册沃支付时间';
COMMENT ON COLUMN "LTZF_INFO"."UNIT_NAME" IS '公司名称';
COMMENT ON COLUMN "LTZF_INFO"."EMP_PHONE" IS '公司固话';
COMMENT ON COLUMN "LTZF_INFO"."EMP_PROVINCE_CODE" IS '公司地址省code';
COMMENT ON COLUMN "LTZF_INFO"."EMP_CITY_CODE" IS '公司地址市code';
COMMENT ON COLUMN "LTZF_INFO"."EMP_ZONE_CODE" IS '公司地址区县code';
COMMENT ON COLUMN "LTZF_INFO"."EMP_ADDR" IS '公司详细地址';
COMMENT ON COLUMN "LTZF_INFO"."CONTACT_LIST" IS '联系人信息';
COMMENT ON COLUMN "LTZF_INFO"."AUTH_NUMBER" IS '征信流水号';
COMMENT ON COLUMN "LTZF_INFO"."OUT_ORDER_ID" IS '联通订单号';
COMMENT ON COLUMN "LTZF_INFO"."APP_NO" IS '申请单号';
COMMENT ON COLUMN "LTZF_INFO"."TOTAL_AMT" IS '总金额';
COMMENT ON COLUMN "LTZF_INFO"."USER_NO" IS '沃支付用户号';
COMMENT ON COLUMN "LTZF_INFO"."NOTYFY_URL" IS '通知地址';
COMMENT ON COLUMN "LTZF_INFO"."MER_NAME" IS '商户名称';
COMMENT ON COLUMN "LTZF_INFO"."CURRENT_STORE_FLAG" IS '是否本门店办理';
COMMENT ON COLUMN "LTZF_INFO"."SALE_ADDRESS" IS '销售地点';
COMMENT ON COLUMN "LTZF_INFO"."BIZ_LICENCE_NO" IS '营业执照号';
COMMENT ON COLUMN "LTZF_INFO"."BIZ_LICENCE_NAME" IS '营业执照名称';
COMMENT ON COLUMN "LTZF_INFO"."RESERVE1" IS '预留1';
COMMENT ON COLUMN "LTZF_INFO"."RESERVE2" IS '预留2';
COMMENT ON COLUMN "LTZF_INFO"."RESERVE3" IS '预留3';


--联通支付--
CREATE TABLE "AIRM"."LTDSJ_INDO" (
            MODEL1 VARCHAR2(100),
            MODEL2 VARCHAR2(100),
            MODEL3 VARCHAR2(100),
            MODEL4 VARCHAR2(100),
            MODEL5 VARCHAR2(100),
            MODEL6 VARCHAR2(100),
            MODEL7 VARCHAR2(100),
            MODEL8 VARCHAR2(100),
            MODEL9 VARCHAR2(100),
            MODEL10 VARCHAR2(100),
            MODEL11 VARCHAR2(100),
            MODEL12 VARCHAR2(100),
            MODEL13 VARCHAR2(100),
            MODEL14 VARCHAR2(100),
            MODEL15 VARCHAR2(100),
            MODEL16 VARCHAR2(100),
            MODEL17 VARCHAR2(100),
            MODEL18 VARCHAR2(100),
            MODEL19 VARCHAR2(100),
            MODEL20 VARCHAR2(100),
            MODEL21 VARCHAR2(100),
            MODEL22 VARCHAR2(100),
            MODEL23 VARCHAR2(100),
            MODEL24 VARCHAR2(100),
            MODEL25 VARCHAR2(100),
            MODEL26 VARCHAR2(100),
            MODEL27 VARCHAR2(100),
            MODEL28 VARCHAR2(100),
            MODEL29 VARCHAR2(100),
            MODEL30 VARCHAR2(100),
            RESERVE1 VARCHAR2(100),
            RESERVE2 VARCHAR2(100),
            RESERVE3 VARCHAR2(100),
);

