spring:
  application:
    name: admin-client

  boot:
    admin:
      client:
        url: http://localhost:8769



  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        enabled: true
        register: true    #是否将自身服务注册到consul中
        hostname: 127.0.0.1
        serviceName: ${spring.application.name}
        tags: test
        instanceId: ${spring.application.name}-${spring.cloud.client.ip-address}-${server.port}  # 服务id
        health-check-path: /actuator/health
        healthCheckInterval: 15s

server:
  port: 8768

management:
  endpoints:
    web:
      exposure:
        include: '*'

  endpoint:
    health:
      show-details: ALWAYS
